import os
import re
import json
import time
from typing import TypedDict, List, Dict, Any
from dotenv import load_dotenv

# Load configurations from your .env file
load_dotenv()

from langgraph.graph import StateGraph, END
from langchain_core.messages import BaseMessage
from langchain_core.prompts import ChatPromptTemplate
# Standard, direct Ollama LLM driver package
from langchain_ollama import OllamaLLM

# =====================================================================
# 1. Direct Mistral Local Initialization
# =====================================================================
# This calls your locally running Mistral instance directly.
# Ensure you have run `ollama pull mistral` in your terminal!
llm = OllamaLLM(model="mistral", temperature=0.1)

# =====================================================================
# 2. Unified Multi-Agent State Definition
# =====================================================================
class AgentState(TypedDict):
    messages: List[BaseMessage]
    raw_alert: Dict[str, Any]
    alert_details: Dict[str, Any]
    generated_query: str
    graph_visualization: Dict[str, Any]  # Generated by Investigator Agent
    typology_reasoning: Dict[str, Any]   # Generated by Typology Scout Agent
    str_form_data: Dict[str, Any]        # Formatted deterministic form fields
    narrative_draft: str                 # Final 5-paragraph SAR narrative text
    forensic_linkages: Dict[str, str]    # UI Auditability Map (node_id -> paragraph)

def clean_and_parse_json(raw_text: str) -> Dict[str, Any]:
    """
    Super-robust JSON parser that handles markdown block ticks, single-quote keys,
    and handles raw unescaped newlines inside string blocks.
    """
    cleaned = raw_text.strip()
    
    # 1. Strip markdown json block wrappers if they exist
    cleaned = re.sub(re.compile(r"^```json", re.IGNORECASE), "", cleaned)
    cleaned = re.sub(re.compile(r"^```", re.IGNORECASE), "", cleaned)
    cleaned = re.sub(re.compile(r"```$", re.IGNORECASE), "", cleaned)
    cleaned = cleaned.strip()
    
    # 2. Convert single-quoted keys/values to double quotes
    cleaned = re.sub(r"\'(\s*[\w_]+\s*)\'\s*:", r'"\1":', cleaned)
    
    # 3. Handle raw unescaped newlines inside JSON string blocks
    # This prevents literal Enters from breaking the structural syntax tokenizer
    cleaned = cleaned.replace("\n", " ").replace("\r", "")
    
    # 4. Attempt to parse out the structured data dictionary
    try:
        return json.loads(cleaned)
    except Exception:
        try:
            # Fallback: Isolate boundaries between curly braces
            match = re.search(r"\{.*\}", cleaned, re.DOTALL)
            if match:
                return json.loads(match.group(0))
        except Exception:
            pass
            
        return {
            "error_parsing": True,
            "raw_output": raw_text
        }

# =====================================================================
# 3. Agent Processing Node Definitions
# =====================================================================
def prep_str_form_fields(state: AgentState) -> Dict[str, Any]:
    """
    Transforms findings and raw alert metadata to map directly into 
    standardized STR form fields matching regulatory templates.
    """
    alert_details = state.get("alert_details", {})
    graph_visualization = state.get("graph_visualization", {})
    
    target_account_id = alert_details.get("account_number", "UNKNOWN")
    detected_reason = alert_details.get("risk_type", "Velocity Flag")
    
    nodes = graph_visualization.get("nodes", [])
    account_holder_name = "UNKNOWN HOLDER"
    if nodes:
        account_holder_name = nodes[0].get("properties", {}).get("holder", "UNKNOWN HOLDER")
    
    # Flat data structure tailored directly to standard STR inputs
    str_form_payload = {
        # Reporting Entity Details
        "fi_name": "SAR MULTI_AGENT_SYSTEM BANK",
        "fi_branch_id": "LOC_PUNE_VIT_01",
        "date_of_report": time.strftime("%Y-%m-%d"),
        
        # Suspect / Entity Subject Information
        "subject_account_id": target_account_id,
        "subject_name": account_holder_name,
        
        # Suspicion Metrics
        "suspicion_reason_primary": detected_reason,
        "first_txn_date": "2026-01-10",
        "last_txn_date": time.strftime("%Y-%m-%d"),
        "total_value_inr": 1250000
    }
    
    return {
        "str_form_data": str_form_payload
    }


def generate_formal_narrative(state: AgentState) -> Dict[str, Any]:
    """
    Invokes Mistral locally to write a strict, formal, 5-paragraph narrative 
    and outputs an auditable interaction mapping for the UI.
    """
    analytical_reasoning = json.dumps(state.get("typology_reasoning", {}))
    graph_metadata = json.dumps(state.get("graph_visualization", {}))
    form_data = json.dumps(state.get("str_form_data", {}))

    prompt = ChatPromptTemplate.from_messages([
        ("system", (
            "You are an expert Anti-Money Laundering (AML) Compliance Officer writing an official report "
            "for the Financial Intelligence Unit (FIU). Convert transactional analysis into a formal "
            "Suspicious Transaction Report narrative.\n\n"
            "Your text MUST follow a strict 5-paragraph structure:\n"
            "Paragraph 1: Subject Overview and account operational setup details.\n"
            "Paragraph 2: Typology Match reasoning matching the behavior pattern ruleset.\n"
            "Paragraph 3: Transaction Flow Forensics (explicit node tracking analysis).\n"
            "Paragraph 4: Documentation Gaps, KYC discrepancies, and compliance observations.\n"
            "Paragraph 5: Final Compliance Action Recommendation.\n\n"
            "Data Inputs for Compilation Context:\n"
            "- Analytical Findings from Typology Scout: {analytical_findings}\n"
            "- Target Form Fields Metadata: {form_metadata}\n"
            "- Graph Topology Node IDs: {graph_json}\n\n"
            "Output Constraints:\n"
            "1. Reference Graph Node IDs directly in your text paragraphs (e.g., 'Account node [1] initiated multiple structured bursts to ATM node [4]').\n"
            "2. Keep the narrative objective, highly factual, and completely free of conversational remarks.\n"
            "3. Return your response strictly as a valid JSON object matching this schema:\n"
            "{{\n"
            "  'narrative': 'The full 5-paragraph text here.',\n"
            "  'forensic_linkages': {{\n"
            "     'Node_ID_From_Graph_JSON_Here': 'Paragraph string or integer number where it was referenced'\n"
            "  }}\n"
            "}}\n"
            "Do not output markdown code ticks (```json) or introductory prose. Return only raw JSON string data."
        )),
        ("human", "Draft the formal STR text summary and compile the UI auditability node interaction link map.")
    ])
    
    # Simple, explicit Mistral chain execution
    chain = prompt | llm
    ai_raw_response = chain.invoke({
        "analytical_findings": analytical_reasoning,
        "form_metadata": form_data,
        "graph_json": graph_metadata
    })
    
    response_content = ai_raw_response.strip()
    
    # SWAP THIS IN FOR THE PARSING LOGIC:
    draft_payload = clean_and_parse_json(response_content)
    
    if "error_parsing" in draft_payload:
        draft_payload = {
            "narrative": f"REPORT EXECUTION EXCEPTION. Raw AI output text follows:\n\n{response_content}",
            "forensic_linkages": {}
        }
        
    return {
        "narrative_draft": draft_payload.get("narrative", ""),
        "forensic_linkages": draft_payload.get("forensic_linkages", {})
    }
# =====================================================================
# 4. State Machine Workflow Construction
# =====================================================================
drafter_workflow = StateGraph(AgentState)

# Add our computational nodes
drafter_workflow.add_node("data_prep", prep_str_form_fields)
drafter_workflow.add_node("narrative_drafter", generate_formal_narrative)

# Construct sequential flow paths
drafter_workflow.add_edge("data_prep", "narrative_drafter")
drafter_workflow.add_edge("narrative_drafter", END)

# Configure start entry point
drafter_workflow.set_entry_point("data_prep")

# Compile state machine graph topology into a runnable application agent
drafter_agent = drafter_workflow.compile()

# =====================================================================
# 5. Local Standalone Test Verification Execution
# =====================================================================
if __name__ == "__main__":
    print("Initializing Drafter Agent framework using local Mistral model...")
    
    # Simulating data coming downstream from Investigator and Scout Agents
    mock_scout_reasoning = {
        "matched_typology": "Structuring / Smurfing Pattern Detected",
        "confidence_score": 0.94,
        "justification": "Account number ACC-7731920 received cascading sequence of automated microdeposits right below KYC alerts."
    }
    
    mock_graph_visualization = {
        "nodes": [
            {"id": "ACC-7731920", "labels": ["Account"], "properties": {"holder": "Avdhoot Patil", "status": "Flagged"}},
            {"id": "NODE_ATM_4", "labels": ["ATM"], "properties": {"location": "Pune, MH"}}
        ],
        "edges": [
            {"id": "E402", "type": "ATM_WITHDRAWAL", "source": "ACC-7731920", "target": "NODE_ATM_4", "properties": {"amount": 49500}}
        ]
    }

    initial_test_state = {
        "messages": [],
        "raw_alert": {"account_number": "ACC-7731920", "risk_type": "High-Frequency Automated Structuring"},
        "alert_details": {"account_number": "ACC-7731920", "risk_type": "High-Frequency Automated Structuring"},
        "generated_query": "MATCH paths... RETURN lists",
        "graph_visualization": mock_graph_visualization,
        "typology_reasoning": mock_scout_reasoning,
        "str_form_data": {},
        "narrative_draft": "",
        "forensic_linkages": {}
    }

    print("\nExecuting Drafter Workflow Pipeline...")
    final_output = drafter_agent.invoke(initial_test_state)
    
    print("\n=====================================================================")
    print("STRUCTURED FORM METADATA GENERATION")
    print("=====================================================================")
    print(json.dumps(final_output["str_form_data"], indent=2))
    
    print("\n=====================================================================")
    print("FORENSIC UI HOVER LINKAGES MAP")
    print("=====================================================================")
    print(json.dumps(final_output["forensic_linkages"], indent=2))

    print("\n=====================================================================")
    print("FINAL 5-PARAGRAPH SUSPICIOUS TRANSACTION REPORT NARRATIVE DRAFT")
    print("=====================================================================")
    print(final_output["narrative_draft"])